name: Matrix_C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: lib
      run: cd src/; make matrix.a
    - name: install
      run: sudo apt install check valgrind lcov libgtest-dev libgmock-dev
  
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: linter
      run: cd src; make check
    - name: test
      run: cd src; make test
  
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v3
    - name: report
      run: make gcov_report
